name = "saicomputech-website"
compatibility_date = "2026-07-28"

[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"
